version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  api:
    build: ./apps/api
    container_name: perfima_api
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB}?authSource=admin
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

volumes:
  mongodb_data:
