name: Tests and Lint
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        working-directory: ./
        run: yarn install

      - name: Run linter
        working-directory: ./
        run: yarn lint

      - name: Build
        working-directory: ./
        run: yarn build

      - name: Run tests
        working-directory: ./
        run: yarn test
